import Link from 'next/link';
import InternalShell from '@/components/InternalShell';

export default function AboutPage(){
  return <InternalShell><main>
    <section className="internal-hero"><div><div className="internal-kicker">About Krida Legal</div><h1>Specialist thinking for moving industries.</h1><p>Krida Legal is structured around industries where rules, rights, technology, commercial relationships and reputation move quickly. The website reflects that approach by connecting issues to sectors, people and current legal context.</p></div><aside className="internal-side"><small>Core sectors</small><div className="tag-list"><span className="tag">Sport</span><span className="tag">Gaming</span><span className="tag">Intellectual Property</span><span className="tag">Business</span></div></aside></section>
    <section className="internal-section"><div className="section-grid"><div><div className="section-label">01 / Approach</div><h2>Start with the problem, not the department.</h2></div><div className="internal-copy"><p>Legal questions rarely stay inside one label. A rights issue can also be a commercial issue. A platform question may also involve regulation, payments, intellectual property or disputes.</p><p>Krida Legal’s digital experience is therefore organised around connected context: what the issue is, where it sits, who is relevant and what current legal signals may affect it.</p></div></div></section>
    <section className="internal-section internal-section--dark"><div className="section-grid"><div><div className="section-label">02 / Digital principle</div><h2>Clarity before promotion.</h2></div><div className="internal-copy"><p>The site is intended to make published information easier to understand and navigate. It is not designed as an advertising funnel or as a substitute for legal advice.</p><Link className="primaryButton" href="/sectors">Explore sectors →</Link></div></div></section>
    <section className="internal-section"><div className="section-grid"><div><div className="section-label">03 / Find context</div><h2>Move from question to relevant information.</h2></div><div className="matter-list"><div className="matter-row"><span>01</span><strong>Explore sectors</strong><Link href="/sectors">↗</Link></div><div className="matter-row"><span>02</span><strong>Find people</strong><Link href="/people">↗</Link></div><div className="matter-row"><span>03</span><strong>Read regulatory signals</strong><Link href="/insights">↗</Link></div></div></div></section>
  </main></InternalShell>
}
